Edege EMC0 enable Wireless and Bluetooth module
edgeble/meta-ecm pull request #3
Opened 2022-08-02 11:28 UTC by moonlinux

Changes help enable linux-firmware recipe and nessary packages to bring the interface up

2022-08-02 11:34 UTC, openedev commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
> +DEPENDS += "openssl-native util-linux-native linux-firmware"
are you copying entire linux-firmware to roofs? what is your ls -l /lib/firmware/* ?

2022-08-02 11:51 UTC, moonlinux commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
> +DEPENDS += "openssl-native util-linux-native linux-firmware"
yes the recipe do compile all the firmware 

du -h /lib/firmware/
 ...
 14M     /lib/firmware/dpaa2/mc
14M     /lib/firmware/dpaa2
734M    /lib/firmware/

2022-08-03 08:08 UTC, moonlinux commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
> +DEPENDS += "openssl-native util-linux-native linux-firmware"
I have fix the firmware needed for Wifi and Bluetooth

root@ecm0-carrier:~# du -h /lib/firmware/
251K    /lib/firmware/ath10k/QCA9887/hw1.0
252K    /lib/firmware/ath10k/QCA9887
3.9M    /lib/firmware/ath10k/WCN3990/hw1.0
3.9M    /lib/firmware/ath10k/WCN3990
514K    /lib/firmware/ath10k/QCA988X/hw2.0
515K    /lib/firmware/ath10k/QCA988X
850K    /lib/firmware/ath10k/QCA9888/hw2.0
851K    /lib/firmware/ath10k/QCA9888
908K    /lib/firmware/ath10k/QCA9984/hw1.0
909K    /lib/firmware/ath10k/QCA9984
639K    /lib/firmware/ath10k/QCA99X0/hw2.0
640K    /lib/firmware/ath10k/QCA99X0
1.7M    /lib/firmware/ath10k/QCA4019/hw1.0
1.7M    /lib/firmware/ath10k/QCA4019
2.8M    /lib/firmware/ath10k/QCA6174/hw3.0
763K    /lib/firmware/ath10k/QCA6174/hw2.1
3.6M    /lib/firmware/ath10k/QCA6174
2.5M    /lib/firmware/ath10k/QCA9377/hw1.0
2.5M    /lib/firmware/ath10k/QCA9377
15M     /lib/firmware/ath10k
1.7M    /lib/firmware/qca
17M     /lib/firmware/

2022-08-03 08:46 UTC, openedev requested changes

2022-08-03 08:46 UTC, openedev commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
> +DEPENDS += "openssl-native util-linux-native linux-firmware"
We need only 7 files mentioned above.

2022-08-03 08:51 UTC, moonlinux commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
> +DEPENDS += "openssl-native util-linux-native linux-firmware"
**linux-firmware-ath10k** and **linux-firmware-qca** will copy relevant firmware files needed for the device

2022-08-03 17:37 UTC, moonlinux commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
> +DEPENDS += "openssl-native util-linux-native linux-firmware"
We have to remove the file while building the image,

2022-08-06 13:47 UTC, openedev commented on recipes-kernel/linux-firmware/linux-firmware_%.bbappend
> +}
What is the /lib/firmware now?

2022-08-06 13:47 UTC, openedev commented on recipes-kernel/linux-firmware/linux-firmware_%.bbappend
> +
This look like a hack to me, just copy on required files.

2022-08-07 13:45 UTC, moonlinux commented on conf/machine/ecm0-carrier.conf
> +"
root@ecm0-carrier:~# ls /lib/firmware/ath10k/QCA9377/hw1.0/
board-2.bin  firmware-5.bin  firmware-sdio-5.bin           notice_ath10k_firmware-6.txt
board.bin    firmware-6.bin  notice_ath10k_firmware-5.txt  notice_ath10k_firmware-sdio-5.txt
root@ecm0-carrier:~#
root@ecm0-carrier:~#
root@ecm0-carrier:~# ls /lib/firmware/qca/
nvm_00230302.bin  rampatch_00230302.bin

2022-08-07 13:51 UTC, moonlinux commented on conf/machine/ecm0-carrier.conf
> +"
root@ecm0-carrier:~# ls /lib/firmware/ath10k/QCA9377/hw1.0/
board-2.bin  firmware-5.bin  firmware-sdio-5.bin           notice_ath10k_firmware-6.txt
board.bin    firmware-6.bin  notice_ath10k_firmware-5.txt  notice_ath10k_firmware-sdio-5.txt
root@ecm0-carrier:~#
root@ecm0-carrier:~#
root@ecm0-carrier:~# ls /lib/firmware/qca/
nvm_00230302.bin  rampatch_00230302.bin

2022-08-07 13:51 UTC, moonlinux commented on recipes-kernel/linux-firmware/linux-firmware_%.bbappend
> +
Ok Thanks process to clean up the rootfs at the very end of the image build-up.
ROOTFS_POSTPROCESS_COMMAND:append = " do_post_rootfs;"

2022-08-07 13:51 UTC, moonlinux commented on recipes-kernel/linux-firmware/linux-firmware_%.bbappend
> +}
since we remove the unnecessary firmware files it content as 
root@ecm0-carrier:~# du -h /lib/firmware/
2.5M    /lib/firmware/ath10k/QCA9377/hw1.0
2.5M    /lib/firmware/ath10k/QCA9377
2.5M    /lib/firmware/ath10k
36K     /lib/firmware/qca
2.6M    /lib/firmware/

2022-08-08 05:47 UTC, openedev commented on conf/machine/ecm0-carrier.conf
> +    ${@bb.utils.contains('DISTRO_FEATURES', 'wifi', 'linux-firmware-ath10k', '', d)} \
One suggestion, create recipes-kernel/linux-firmware/linux-firmware_%.bbappend
and add new PACKAGES for linux-firmware-ath10k-qca9377 take a reference from openembedded-core/meta/recipes-kernel/linux-firmware/linux-firmware_20220610.bb

This way you can avoid unneeded copy.

2022-08-08 14:49 UTC, moonlinux commented on conf/machine/ecm0-carrier.conf
> +    ${@bb.utils.contains('DISTRO_FEATURES', 'wifi', 'linux-firmware-ath10k', '', d)} \
Ok I have converted these as packagegroup-firmware-qca9377.bb in the next version.

2022-08-08 15:22 UTC, openedev commented on conf/machine/include/edge-compute-module-0.inc
> +	rm ${IMAGE_ROOTFS}/lib/firmware/qca/rampatch_usb_00130201.bin
Do we still need this even if we have qca9377 package?

2022-08-08 15:36 UTC, moonlinux commented on conf/machine/include/edge-compute-module-0.inc
> +	rm ${IMAGE_ROOTFS}/lib/firmware/qca/rampatch_usb_00130201.bin
List firmware in the rootfs.
```
root@ecm0-carrier:~# ls /lib/firmware/qca/
nvm_00230302.bin  rampatch_00230302.bin
root@ecm0-carrier:~#
```

I have checked the BT feature is working with see below.

```
root@ecm0-carrier:~# bluetoothctl
Agent registered
[CHG] Controller B8:4D:43:38:A3:D5 Pairable: yes
[bluetooth]# show
Controller B8:4D:43:38:A3:D5 (public)
        Name: BlueZ 5.64
        Alias: BlueZ 5.64
        Class: 0x00000000
        Powered: yes
        Discoverable: yes
        DiscoverableTimeout: 0x00000000
        Pairable: yes
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0540
        Discovering: no
        Roles: central
        Roles: peripheral
Advertising Features:
        ActiveInstances: 0x00 (0)
        SupportedInstances: 0x05 (5)
        SupportedIncludes: tx-power
        SupportedIncludes: appearance
        SupportedIncludes: local-name
[bluetooth]# scan on
Discovery started
[CHG] Controller B8:4D:43:38:A3:D5 Discovering: yes
[NEW] Device B0:68:E6:C1:B0:52 SONY KD-55A9G
[NEW] Device D4:8A:39:C2:CA:5A D4-8A-39-C2-CA-5A
[CHG] Device D4:8A:39:C2:CA:5A Name: Anand's Galaxy M51
[CHG] Device D4:8A:39:C2:CA:5A Alias: Anand's Galaxy M51
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001105-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000110a-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001112-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001115-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001116-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000111f-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000112d-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000112f-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001132-0000-1000-8000-00805f9b34fb
[NEW] Device 69:10:3D:D1:7B:F3 69-10-3D-D1-7B-F3
[DEL] Device B0:68:E6:C1:B0:52 SONY KD-55A9G
[NEW] Device B0:68:E6:C1:B0:52 SONY KD-55A9G
[CHG] Device B0:68:E6:C1:B0:52 RSSI: -77
[CHG] Device B0:68:E6:C1:B0:52 UUIDs: 0000110a-0000-1000-8000-00805f9b34fb
[CHG] Device B0:68:E6:C1:B0:52 UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device B0:68:E6:C1:B0:52 UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device B0:68:E6:C1:B0:52 UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device B0:68:E6:C1:B0:52 UUIDs: 00000000-0000-0000-0000-000000000000
[CHG] Device D4:8A:39:C2:CA:5A RSSI: -42
[NEW] Device 40:C9:EF:A4:B2:E9 40-C9-EF-A4-B2-E9
[CHG] Device D4:8A:39:C2:CA:5A Connected: yes
Request confirmation
[agent] Confirm passkey 824899 (yes/no): yes
[CHG] Device B0:68:E6:C1:B0:52 RSSI: -98
[CHG] Device D4:8A:39:C2:CA:5A Modalias: bluetooth:v0075p0100d0201
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001105-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000110a-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001112-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001115-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001116-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000111f-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000112d-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 0000112f-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001132-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001800-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A UUIDs: 00001801-0000-1000-8000-00805f9b34fb
[CHG] Device D4:8A:39:C2:CA:5A ServicesResolved: yes
[CHG] Device D4:8A:39:C2:CA:5A Paired: yes
[NEW] Device 4C:EA:AE:82:9D:8A 4C-EA-AE-82-9D-8A
[DEL] Device 69:10:3D:D1:7B:F3 69-10-3D-D1-7B-F3
[CHG] Device D4:8A:39:C2:CA:5A ServicesResolved: no
[CHG] Device D4:8A:39:C2:CA:5A Connected: no
[NEW] Device 55:7C:AE:BD:24:9D 55-7C-AE-BD-24-9D
[DEL] Device 40:C9:EF:A4:B2:E9 40-C9-EF-A4-B2-E9
[CHG] Device B0:68:E6:C1:B0:52 RSSI: -79
[CHG] Device 4C:EA:AE:82:9D:8A Name: OPPO A16
[CHG] Device 4C:EA:AE:82:9D:8A Alias: OPPO A16
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00001105-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 0000110a-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 0000110c-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 0000110e-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00001112-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00001115-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00001116-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 0000111f-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 0000112f-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00001200-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00001132-0000-1000-8000-00805f9b34fb
[CHG] Device 4C:EA:AE:82:9D:8A UUIDs: 00000000-0000-0000-0000-000000000000

```

2022-08-18 07:25 UTC, openedev requested changes

2022-08-18 07:25 UTC, openedev commented on README.md
> +  ${TOPDIR}/../meta-openembedded/meta-oe\
space

2022-08-18 07:25 UTC, openedev commented on README.md
> +  ${TOPDIR}/../meta-openembedded/meta-python\
ditto

2022-08-18 07:25 UTC, openedev commented on README.md
> +  ${TOPDIR}/../meta-openembedded/meta-networking\
ditto

2022-08-18 07:32 UTC, moonlinux reviewed
ok

2022-08-18 07:32 UTC, moonlinux commented on README.md
> +  ${TOPDIR}/../meta-openembedded/meta-networking\
ok

2022-08-18 07:32 UTC, moonlinux commented on README.md
> +  ${TOPDIR}/../meta-openembedded/meta-python\
ok

2022-08-18 13:54 UTC, openedev commented on recipes-kernel/linux/files/rv1126-ecm0.cfg
> +CONFIG_ROCKCHIP_SARADC=y
last 3 added again?

2022-08-18 13:55 UTC, openedev commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
update SRCREV for u-boot as well.

2022-08-18 14:02 UTC, moonlinux reviewed
Thanks for your comments.

2022-08-18 14:02 UTC, moonlinux commented on recipes-kernel/linux/linux-next_5.19-rc6.bb
updated in a separate patch.

2022-08-18 14:02 UTC, moonlinux commented on recipes-kernel/linux/files/rv1126-ecm0.cfg
> +CONFIG_ROCKCHIP_SARADC=y
ok I missed this.

2022-08-18 14:17 UTC, openedev approved these changes

2022-08-18 14:17 UTC, merged

2022-08-18 16:52 UTC, openedev commented
Fixes #2